spring.datasource.url=jdbc:mysql://localhost:3306/smartdata?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.main.allow-circular-references=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jira.baseurl=https://empresa-steam.atlassian.net
jira.email=
jira.token=
jira.project.key=KAN

slack.webhook.url=

sla.prazo.critico=1
sla.prazo.medio=4
sla.prazo.baixo=24

aws.bucket-nome=smart-data-bucket-java
aws.region=us-east-1
aws.secretKey=
aws.sessionToken=
aws.accessKeyId=